

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>css modelos</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php  $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.2.min.js', 'text/javascript');?>
<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.8.21.custom.min.js', 'text/javascript');?>
    <link type="text/css" href="<?php echo $this->baseUrl().'/css/pepper-grinder/jquery-ui-1.8.21.custom.css'?>" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/layout/reset.css" rel="stylesheet" type="text/css" media="all" />
    <link href="<?php echo $this->baseUrl(); ?>/css/layout/typography.css" rel="stylesheet" type="text/css" media="all" />
    <link href="<?php echo $this->baseUrl(); ?>/css/layout/main.css" rel="stylesheet" type="text/css" />
    
      <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap.css');?>
      <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap-responsive.css');?>
      <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/docs.css');?>

<script>

	$(document).ready(function(){
            
                     $('#msg1').hide(); 
                     $('#msg0').show(); 
                var token = 0;
            setInterval(function(){
                    // alert('ok');
             //   $('p').each(function(index){
             
                   if( token == 0){
                      // alert('FECHADO');
                         $('#msg1').hide(); 
                         $('#msg0').show(); 
                       token = 1;
                   }else{
                     //   alert('ABERTO');
                         $('#msg0').hide(); 
                         $('#msg1').show(); 
                        token = 0 ;
                   }
                   
                  
                    
            //    });
                   
               },5000)
       
         //   $("#flashSucess").delay(3000).hide();
		$("#flashSuccess").delay(200).slideUp('1000');     
        
//                $('li.headlink').hover(
//			function() { $('ul', this).css('display', 'block'); },
//			function() { $('ul', this).css('display', 'none'); });
                $( "#tabs" ).tabs();        

	});
        
	

</script>  
</head>
<body>
    
        <?php    $arMenu = array(
            'Início'=>array('uri'=>'/'),
            'Vistorias'=>array('uri'=>'#vistorias',
                'child'=>array(
                    'Cadastrar'=>array('uri'=>'/vistorias/cadastrar/'),
                    'Consultar/Editar'=>array('uri'=>'/vistorias/consultar/'),
                    'Criar campos'=>array('uri'=>'/campos/criar/'),
                    'Consultar campos'=>array('uri'=>'/campos/consultar/'),
                    'Montar checklist'=>array('uri'=>'/checklist/montar'),
                )),
             'Clientes'=>array('uri'=>'#clientes',
                 'child'=>array(
                     'Cadastrar'=>array('uri'=>'/clientes/cadastrar/'),
                     'Consultar/Editar'=>array('uri'=>'/clientes/consultar')
                 )),
             'Usuários'=>array('uri'=>'#usuarios',
                 'child'=>array(
                     'Cadastrar'=>array('uri'=>'/usuarios/cadastrar/'),
                     'Consultar/Editar'=>array('uri'=>'/usuarios/consultar')
                 ))  
                );?>
<div id="mainwrap">	
    
    

                <?php echo $this->flashMessages(); ?>
           
    
        <!--NOTIFICATOR -->
        
        
        
        
        
<!--BEGIN OF TERMS OF USE. DO NOT EDIT OR DELETE THESE LINES. IF YOU EDIT OR DELETE THESE LINES AN ALERT MESSAGE MAY APPEAR WHEN TEMPLATE WILL BE ONLINE-->

 <!--END OF TERMS OF USE-->
	<div id="leftcol">
            
            <div id="logo"><img src="<?php echo $this->baseUrl();?>/images/GvisLogo.png"/></div>
           
        
            <?php  echo $this->montar($arMenu);?>
      

        <div class="module-box grey1">
        	<h2 class="none">Missão</h2>
        	<div class="module-content">
                <p id="msg0">Trazer valor e benefícios ao mundo dos negócios.</p>
                <p id="msg1">Importe-se apenas com o que realmente interessa.</p>
            </div>
        </div>
        <div class="module-box">
        	<h2 class="orange">News</h2>
            <div class="module-content">
            	<ul class="none">
                	<li>
                    	<strong><a href="?" class="black">21 December 2008</a></strong>
                        <p>Novidades 1 - texto completo</p>
                        <a href="?">Read news</a>
                    </li>
                    <li>
                    	<strong><a href="?" class="black">21 December 2008</a></strong>
                        <p>Novidades 2 texto completo</p>
                        <a href="?">Read news</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="module-box">
        	<h2 class="grey">Deseja receber novidades?</h2>
            <div class="module-content grey">
            	<label for="email">Seu e-mail:</label>
                <input type="text" style="with: 160px;" value="" id="email" />
                <input class="btn" type="submit" value="OK" />
            </div>
        </div>
    </div>
    <div id="rightcol">
    	<div id="header" class="clearfix">
        	<div id="call">TELEFONE</div>
            <div id="search"><input type="text" style="with: 160px;" value="" id="input-search" /><input type="submit" value="ok" id="ok" /></div>
        </div>
        <div id="banner">
            <img src="<?php echo $this->baseUrl(); ?>/images/photo.jpg"/>
        </div>
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="footer">
        	<div id="botnav" style="text-align:center">
            	<ul class="clearfix">
                	<li><a href="?">Sobre Nós</a></li>
                    <li><a href="?">Portfólio</a></li>
                    <li><a href="?">Serviços</a></li>
                    <li><a href="?">Parceiros</a></li>
                    <li><a href="?">Contato</a></li>
                </ul>
            </div>
            <div id="copyright">
            	Copyright (c) 2003-2009 &nbsp;|&nbsp; SuperNova TI - GVIS
            </div>
        </div>
    </div>
</div>
</body>
</html>
