<html>
    <head>
      <?php  $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.7.2.min.js', 'text/javascript');?>
      <?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.8.21.custom.min.js', 'text/javascript');?>
      <?php $this->headLink()->prependStylesheet($this->baseUrl().'/css/bootstrap.css');?>
      <?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/bootstrap-responsive.css');?>
      <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/docs.css');?>
    </head>
    <body data-spy="scroll" data-target=".subnav" data-offset="50">

   
    <div class="container-fluid">
    <div class="row-fluid">
        <div class="span2" style="background-color: #EEEEEE ">
            <ul>
                <ol>Item 1</ol>
                <ol>Item 2</ol>
                <ol>Item 3</ol>
                <ol>Item 4</ol>
            </ul>
        </div>
        <div class="span10" style="background-color: #EEEEEE ">
            <h2>Layout</h2>
        <?php echo $this->layout()->content; ?>
            
            <input class="input" type="text" value="" height="50">


        </div>
    </div>
    </div>
    </body>
</html>
